Utilities:
  - "Luz"
  - "Endesa"
  - "Iberdrola"
  - "*Energia"
  - "Netflix"
  - "HBO"
  - "Disney.*Plus"
  - "Securitas.*"
  - "Prosegur"
  - "Comunidad|HOA"
  - "IBI|Council.*Tax"
  - "Ayto.*"
  - "Canal.*Isabel.*II"
  - "Digi.*Spain"
  - "Caldera"
  - "*Seguros"
Leisure:
  - "Restaurant.*"
  - "Uber.*Eats"
  - "Just.*Eat"
  - "Hotel"
  - "Taxi"
  - "Freenow"
  - "Viaje"
  - "Cafe"
  - "Croissant"
  - "Pasteleria|Boulangery|Cafe.*"
  - "Bar.*"
Grocery shopping:
  - "Alcampo"
  - "Auchan"
  - "Aldi"
  - "Mercadona"
  - "Ahorramas"
  - "Lidl"
  - "BM.*"
  - "Tesco.*"
  - "Hipercor"
Online shopping:
  - "Amazon"
  - "Amzn"
  - "H&M"
  - "H M"
  - "El Corte Ingles"
  - "Temu"
  - "Fnac"
  - "Aliexpress"
Car:
  - "Gasolinera"
  - "Repsol"
  - "BP"
  - "Moeve"
  - "Peaje"
  - "Autopista"
  - "Reparmovil"
  - "Area.*Servici.*"
  - ".*park.*"
Health:
  - "Farmacia|Pharmacy"
  - "Hospital"
Education:
  - "Escuela.*"
  - "Colegio.*|School.*"
Investments:
  - ".*Inversion|Investment.*"
Income:
  - "Ingreso|Income|Transfer.*"
